# Generated by Django 5.2.16 on 2026-07-29 06:56

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.knowledge_base.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "version_id",
                    models.CharField(max_length=140, primary_key=True, serialize=False),
                ),
                ("version_or_edition", models.CharField(blank=True, max_length=100)),
                ("revision_or_effective_date", models.DateField(blank=True, null=True)),
                ("revision_label", models.CharField(blank=True, max_length=50)),
                (
                    "source_file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.knowledge_base.models.document_upload_path,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("file_size", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(max_length=100)),
                ("extracted_text", models.TextField(blank=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("extraction_warnings", models.JSONField(blank=True, default=list)),
                ("extraction_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "document_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=300)),
                ("document_code", models.CharField(blank=True, max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("safety_handbook", "Safety handbook"),
                            ("manual", "Manual"),
                            ("procedure", "Procedure"),
                            ("troubleshooting_guide", "Troubleshooting guide"),
                            ("training", "Training material"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=150)),
                ("equipment_family", models.CharField(blank=True, max_length=200)),
                ("equipment_model", models.CharField(blank=True, max_length=200)),
                ("subsystem", models.CharField(blank=True, max_length=150)),
                ("version_or_edition", models.CharField(blank=True, max_length=100)),
                ("revision_or_effective_date", models.DateField(blank=True, null=True)),
                ("revision_label", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(default="English", max_length=50)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "current_version_verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            (
                                "requires_version_verification",
                                "Requires current-version verification",
                            ),
                            ("verified_current", "Verified current"),
                        ],
                        default="unverified",
                        max_length=40,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "safety_priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("not_processed", "Not processed"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("manual_review", "Manual review required"),
                        ],
                        default="not_processed",
                        max_length=20,
                    ),
                ),
                ("processing_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["manufacturer", "document_code", "title"],
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("process", "Process"), ("reprocess", "Reprocess")],
                        default="process",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("manual_review", "Manual review required"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="knowledge_base.documentversion",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="knowledge_base.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="documentversion",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="knowledge_base.knowledgedocument",
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "chunk_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("chapter", models.CharField(blank=True, max_length=300)),
                ("section", models.CharField(blank=True, max_length=300)),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=150)),
                ("equipment_family", models.CharField(blank=True, max_length=200)),
                ("subsystem", models.CharField(blank=True, max_length=150)),
                ("safety_priority", models.CharField(max_length=20)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("contains_warning", models.BooleanField(default=False)),
                ("contains_caution", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("requires_correction", "Requires correction"),
                            ("excluded", "Excluded from retrieval"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("processing_warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="knowledge_base.documentchunk",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge_base.documentversion",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge_base.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document_version", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_version", "sequence"),
                        name="unique_chunk_sequence_per_version",
                    )
                ],
            },
        ),
    ]
