# Generated by Django 5.2.16 on 2026-07-30 02:17

import uuid
from typing import Any

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def inherit_chunk_document_metadata(apps: Any, schema_editor: Any) -> None:
    DocumentChunk = apps.get_model("knowledge_base", "DocumentChunk")
    for chunk in DocumentChunk.objects.select_related("document").iterator():
        chunk.equipment_model = chunk.document.equipment_model
        chunk.access_level = chunk.document.access_level
        chunk.save(update_fields=["equipment_model", "access_level"])


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkSplitCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_content_hash", models.CharField(max_length=64)),
                ("segment_payload", models.JSONField(default=list)),
                ("artifact_changes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("stale", "Stale — revalidation required"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="documentchunk",
            name="unique_chunk_sequence_per_version",
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="access_level",
            field=models.CharField(default="internal", max_length=20),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="equipment_model",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="is_current_generation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="origin",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("correction", "Correction child"),
                ],
                default="generated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="parent_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_children",
                to="knowledge_base.documentchunk",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="retrieval_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_document_chunks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="reviewer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            inherit_chunk_document_metadata,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("requires_correction", "Requires correction"),
                    ("excluded", "Excluded from retrieval"),
                    ("superseded", "Superseded by correction"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="sequence",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_generation", True)),
                fields=("document_version", "sequence"),
                name="unique_current_chunk_sequence_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current_generation", True), ("retrieval_enabled", True)
                ),
                fields=("document_version", "content_hash"),
                name="unique_active_chunk_content_per_version",
            ),
        ),
        migrations.AddField(
            model_name="chunksplitcorrection",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chunk_split_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chunksplitcorrection",
            name="document_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="split_corrections",
                to="knowledge_base.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="chunksplitcorrection",
            name="source_chunk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="split_corrections",
                to="knowledge_base.documentchunk",
            ),
        ),
    ]
