# Generated by Django 5.2.16 on 2026-07-31 02:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0003_chunkmetadatacorrection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="origin",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("correction", "Correction child"),
                    ("correction_replacement", "Correction replacement"),
                ],
                default="generated",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ChunkReplacementCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_content_hash", models.CharField(max_length=64)),
                ("new_content_hash", models.CharField(max_length=64)),
                ("corrected_content", models.TextField()),
                ("reason", models.TextField()),
                ("reviewer_notes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("stale", "Stale — revalidation required"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunk_replacement_corrections",
                        to="knowledge_base.knowledgedocument",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunk_replacement_corrections",
                        to="knowledge_base.documentversion",
                    ),
                ),
                (
                    "replaced_child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_correction",
                        to="knowledge_base.documentchunk",
                    ),
                ),
                (
                    "replacement_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_result_for",
                        to="knowledge_base.documentchunk",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunk_replacement_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
