# Generated by Django 5.2.16 on 2026-07-31 04:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0004_alter_documentchunk_origin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorIndexVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collection_name", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("validating", "Validating"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("retired", "Retired"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("model_name", models.CharField(max_length=200)),
                ("model_identity", models.CharField(max_length=300)),
                ("vector_dimension", models.PositiveIntegerField()),
                ("distance_metric", models.CharField(default="cosine", max_length=20)),
                ("normalization", models.CharField(max_length=100)),
                ("corpus_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                ("eligible_chunk_count", models.PositiveIntegerField(default=0)),
                ("indexed_chunk_count", models.PositiveIntegerField(default=0)),
                ("failure_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="one_active_vector_index",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChunkEmbeddingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vector_point_id", models.UUIDField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("embedding_input_hash", models.CharField(max_length=64)),
                ("model_identity", models.CharField(max_length=300)),
                ("vector_dimension", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding_records",
                        to="knowledge_base.documentchunk",
                    ),
                ),
                (
                    "index_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding_records",
                        to="knowledge_base.vectorindexversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index_version", "chunk"),
                        name="unique_chunk_per_vector_index",
                    ),
                    models.UniqueConstraint(
                        fields=("index_version", "vector_point_id"),
                        name="unique_point_per_vector_index",
                    ),
                ],
            },
        ),
    ]
